repos:
  - repo: https://github.com/OCA/maintainer-tools
    rev: 9a170331575a265c092ee6b24b845ec508e8ef75
    hooks:
      - id: oca-gen-addon-readme
        args:
          - --addons-dir=.
          - --org-name=agungsepruloh
          - --repo-name=employee_contract
          - --branch=19.0
      - id: oca-gen-addons-table
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
